apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rag2-main-aug15-2 
  janus-idp.io/tekton: rag2-main-aug15-2
  backstage.io/kubernetes-id: rag2-main-aug15-2
  backstage.io/kubernetes-namespace: rag2-main-aug15-2 
  app.kubernetes.io/part-of: rag2-main-aug15-2
resources: 
- application-dev.yaml