kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rag2-main-aug15-2-dsp-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: rag2-main-aug15-2-dsp-job
    namespace: rag2-main-aug15-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rag2-main-aug15-2-dsp-job-role